version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker login -u $DOCKER_ID -p $DOCKER_PASSWORD registry.uw.systems
      - run: docker build -t nginx-prometheus:$CIRCLE_SHA1 .
      - run: docker tag nginx-prometheus:$CIRCLE_SHA1 nginx-prometheus:latest
      - run: docker push nginx-prometheus:$CIRCLE_SHA1
      - run: docker push nginx-prometheus:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: cbc-dev
          filters:
            branches:
              only: master
